version: '3'
services:
  app:
    image: laravel-musicapp
    build:
      context: ./
    volumes:
      - .:/var/www
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=local
      - UPLOAD_LIMIT=64M
  scheduler:
    image: laravel-musicapp
    container_name: laravel-scheduler
    depends_on:
      - app
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV: local
      - CONTAINER_ROLE: scheduler
