version: '3'
services:
  app:
    build:
      context: ./
    volumes:
      - .:/var/www
    ports:
      - "8080:8080"
    command: ["su", "webuser", "-c", "php artisan schedule:work"]
    environment:
      - APP_ENV=local
