name: Deploy Web App to Cloud Server

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v3
      - name: Set up Laravel
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: 8.1.10
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install dependencies
        run: composer install
      - name: Generate key
        run: php artisan key:generate --ansi
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Deploy to Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.INFINITYFREE_HOST}}
          username: ${{secrets.INITIFYFREE_USERNAME}}
          password: ${{secrets.INITIFYFREE_PASSWORD}}
          script: |
            cd htdocs
            rm -rf *
            cp -R ../public.* .

