name: Check code changes
on:
  pull_request:
    branches: [ 'master' ]

jobs:
  check-code-changes:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Check code changes
          uses: tj-actions/verify-changed-files@v16